/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Configuracoes = IDL.Record({
  'moeda' : IDL.Text,
  'tema' : IDL.Variant({ 'claro' : IDL.Null, 'escuro' : IDL.Null }),
  'nomeNegocio' : IDL.Text,
});
export const FiadoId = IDL.Nat;
export const Time = IDL.Int;
export const ProdutoId = IDL.Nat;
export const VendaItem = IDL.Record({
  'produtoId' : ProdutoId,
  'preco' : IDL.Nat,
  'quantidade' : IDL.Nat,
});
export const EstadoFiado = IDL.Variant({
  'pendente' : IDL.Null,
  'pago' : IDL.Null,
});
export const Fiado = IDL.Record({
  'id' : FiadoId,
  'total' : IDL.Nat,
  'data' : Time,
  'dataPagamento' : IDL.Opt(Time),
  'clienteNome' : IDL.Text,
  'itens' : IDL.Vec(VendaItem),
  'clienteTelefone' : IDL.Text,
  'estado' : EstadoFiado,
});
export const FuncionarioId = IDL.Nat;
export const Papel = IDL.Variant({
  'admin' : IDL.Null,
  'caixa' : IDL.Null,
  'garcom' : IDL.Null,
});
export const Funcionario = IDL.Record({
  'id' : FuncionarioId,
  'ativo' : IDL.Bool,
  'nome' : IDL.Text,
  'pinHash' : IDL.Vec(IDL.Nat8),
  'papel' : Papel,
});
export const Categoria = IDL.Variant({
  'outros' : IDL.Null,
  'bebida' : IDL.Null,
  'comida' : IDL.Null,
});
export const Unidade = IDL.Variant({
  'lata' : IDL.Null,
  'garrafa' : IDL.Null,
  'unidade' : IDL.Null,
  'prato' : IDL.Null,
});
export const Produto = IDL.Record({
  'id' : ProdutoId,
  'categoria' : Categoria,
  'ativo' : IDL.Bool,
  'nome' : IDL.Text,
  'stockAtual' : IDL.Nat,
  'stockMinimo' : IDL.Nat,
  'unidade' : Unidade,
  'precoVenda' : IDL.Nat,
  'precoCusto' : IDL.Nat,
});
export const VendaId = IDL.Nat;
export const MetodoPagamento = IDL.Variant({
  'mpesa' : IDL.Null,
  'outro' : IDL.Null,
  'emola' : IDL.Null,
  'dinheiro' : IDL.Null,
});
export const Venda = IDL.Record({
  'id' : VendaId,
  'desconto' : IDL.Nat,
  'total' : IDL.Nat,
  'metodoPagamento' : MetodoPagamento,
  'funcionarioId' : FuncionarioId,
  'dataHora' : Time,
  'observacoes' : IDL.Text,
  'itens' : IDL.Vec(VendaItem),
});

export const idlService = IDL.Service({
  'atualizarConfiguracoes' : IDL.Func([Configuracoes], [], []),
  'consultarConfiguracoes' : IDL.Func([], [Configuracoes], ['query']),
  'consultarFiados' : IDL.Func([], [IDL.Vec(Fiado)], ['query']),
  'consultarFuncionarios' : IDL.Func([], [IDL.Vec(Funcionario)], ['query']),
  'consultarProdutos' : IDL.Func([], [IDL.Vec(Produto)], ['query']),
  'consultarVendas' : IDL.Func([], [IDL.Vec(Venda)], ['query']),
  'criarFiado' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(VendaItem), IDL.Nat],
      [Fiado],
      [],
    ),
  'criarFuncionario' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat8), Papel],
      [Funcionario],
      [],
    ),
  'criarProduto' : IDL.Func(
      [IDL.Text, Categoria, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, Unidade],
      [Produto],
      [],
    ),
  'criarVenda' : IDL.Func(
      [
        IDL.Vec(VendaItem),
        IDL.Nat,
        IDL.Nat,
        MetodoPagamento,
        FuncionarioId,
        IDL.Text,
      ],
      [Venda],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Configuracoes = IDL.Record({
    'moeda' : IDL.Text,
    'tema' : IDL.Variant({ 'claro' : IDL.Null, 'escuro' : IDL.Null }),
    'nomeNegocio' : IDL.Text,
  });
  const FiadoId = IDL.Nat;
  const Time = IDL.Int;
  const ProdutoId = IDL.Nat;
  const VendaItem = IDL.Record({
    'produtoId' : ProdutoId,
    'preco' : IDL.Nat,
    'quantidade' : IDL.Nat,
  });
  const EstadoFiado = IDL.Variant({ 'pendente' : IDL.Null, 'pago' : IDL.Null });
  const Fiado = IDL.Record({
    'id' : FiadoId,
    'total' : IDL.Nat,
    'data' : Time,
    'dataPagamento' : IDL.Opt(Time),
    'clienteNome' : IDL.Text,
    'itens' : IDL.Vec(VendaItem),
    'clienteTelefone' : IDL.Text,
    'estado' : EstadoFiado,
  });
  const FuncionarioId = IDL.Nat;
  const Papel = IDL.Variant({
    'admin' : IDL.Null,
    'caixa' : IDL.Null,
    'garcom' : IDL.Null,
  });
  const Funcionario = IDL.Record({
    'id' : FuncionarioId,
    'ativo' : IDL.Bool,
    'nome' : IDL.Text,
    'pinHash' : IDL.Vec(IDL.Nat8),
    'papel' : Papel,
  });
  const Categoria = IDL.Variant({
    'outros' : IDL.Null,
    'bebida' : IDL.Null,
    'comida' : IDL.Null,
  });
  const Unidade = IDL.Variant({
    'lata' : IDL.Null,
    'garrafa' : IDL.Null,
    'unidade' : IDL.Null,
    'prato' : IDL.Null,
  });
  const Produto = IDL.Record({
    'id' : ProdutoId,
    'categoria' : Categoria,
    'ativo' : IDL.Bool,
    'nome' : IDL.Text,
    'stockAtual' : IDL.Nat,
    'stockMinimo' : IDL.Nat,
    'unidade' : Unidade,
    'precoVenda' : IDL.Nat,
    'precoCusto' : IDL.Nat,
  });
  const VendaId = IDL.Nat;
  const MetodoPagamento = IDL.Variant({
    'mpesa' : IDL.Null,
    'outro' : IDL.Null,
    'emola' : IDL.Null,
    'dinheiro' : IDL.Null,
  });
  const Venda = IDL.Record({
    'id' : VendaId,
    'desconto' : IDL.Nat,
    'total' : IDL.Nat,
    'metodoPagamento' : MetodoPagamento,
    'funcionarioId' : FuncionarioId,
    'dataHora' : Time,
    'observacoes' : IDL.Text,
    'itens' : IDL.Vec(VendaItem),
  });
  
  return IDL.Service({
    'atualizarConfiguracoes' : IDL.Func([Configuracoes], [], []),
    'consultarConfiguracoes' : IDL.Func([], [Configuracoes], ['query']),
    'consultarFiados' : IDL.Func([], [IDL.Vec(Fiado)], ['query']),
    'consultarFuncionarios' : IDL.Func([], [IDL.Vec(Funcionario)], ['query']),
    'consultarProdutos' : IDL.Func([], [IDL.Vec(Produto)], ['query']),
    'consultarVendas' : IDL.Func([], [IDL.Vec(Venda)], ['query']),
    'criarFiado' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(VendaItem), IDL.Nat],
        [Fiado],
        [],
      ),
    'criarFuncionario' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat8), Papel],
        [Funcionario],
        [],
      ),
    'criarProduto' : IDL.Func(
        [IDL.Text, Categoria, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, Unidade],
        [Produto],
        [],
      ),
    'criarVenda' : IDL.Func(
        [
          IDL.Vec(VendaItem),
          IDL.Nat,
          IDL.Nat,
          MetodoPagamento,
          FuncionarioId,
          IDL.Text,
        ],
        [Venda],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };