/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Categoria = { 'outros' : null } |
  { 'bebida' : null } |
  { 'comida' : null };
export interface Configuracoes {
  'moeda' : string,
  'tema' : { 'claro' : null } |
    { 'escuro' : null },
  'nomeNegocio' : string,
}
export type EstadoFiado = { 'pendente' : null } |
  { 'pago' : null };
export interface Fiado {
  'id' : FiadoId,
  'total' : bigint,
  'data' : Time,
  'dataPagamento' : [] | [Time],
  'clienteNome' : string,
  'itens' : Array<VendaItem>,
  'clienteTelefone' : string,
  'estado' : EstadoFiado,
}
export type FiadoId = bigint;
export interface Funcionario {
  'id' : FuncionarioId,
  'ativo' : boolean,
  'nome' : string,
  'pinHash' : Uint8Array,
  'papel' : Papel,
}
export type FuncionarioId = bigint;
export type MetodoPagamento = { 'mpesa' : null } |
  { 'outro' : null } |
  { 'emola' : null } |
  { 'dinheiro' : null };
export type Papel = { 'admin' : null } |
  { 'caixa' : null } |
  { 'garcom' : null };
export interface Produto {
  'id' : ProdutoId,
  'categoria' : Categoria,
  'ativo' : boolean,
  'nome' : string,
  'stockAtual' : bigint,
  'stockMinimo' : bigint,
  'unidade' : Unidade,
  'precoVenda' : bigint,
  'precoCusto' : bigint,
}
export type ProdutoId = bigint;
export type Time = bigint;
export type Unidade = { 'lata' : null } |
  { 'garrafa' : null } |
  { 'unidade' : null } |
  { 'prato' : null };
export interface Venda {
  'id' : VendaId,
  'desconto' : bigint,
  'total' : bigint,
  'metodoPagamento' : MetodoPagamento,
  'funcionarioId' : FuncionarioId,
  'dataHora' : Time,
  'observacoes' : string,
  'itens' : Array<VendaItem>,
}
export type VendaId = bigint;
export interface VendaItem {
  'produtoId' : ProdutoId,
  'preco' : bigint,
  'quantidade' : bigint,
}
export interface _SERVICE {
  'atualizarConfiguracoes' : ActorMethod<[Configuracoes], undefined>,
  'consultarConfiguracoes' : ActorMethod<[], Configuracoes>,
  'consultarFiados' : ActorMethod<[], Array<Fiado>>,
  'consultarFuncionarios' : ActorMethod<[], Array<Funcionario>>,
  'consultarProdutos' : ActorMethod<[], Array<Produto>>,
  'consultarVendas' : ActorMethod<[], Array<Venda>>,
  'criarFiado' : ActorMethod<[string, string, Array<VendaItem>, bigint], Fiado>,
  'criarFuncionario' : ActorMethod<[string, Uint8Array, Papel], Funcionario>,
  'criarProduto' : ActorMethod<
    [string, Categoria, bigint, bigint, bigint, bigint, Unidade],
    Produto
  >,
  'criarVenda' : ActorMethod<
    [Array<VendaItem>, bigint, bigint, MetodoPagamento, FuncionarioId, string],
    Venda
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];