/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type FuncionarioId = bigint;
export interface Configuracoes {
    moeda: string;
    tema: Variant_claro_escuro;
    nomeNegocio: string;
}
export type Time = bigint;
export type ProdutoId = bigint;
export interface Venda {
    id: VendaId;
    desconto: bigint;
    total: bigint;
    metodoPagamento: MetodoPagamento;
    funcionarioId: FuncionarioId;
    dataHora: Time;
    observacoes: string;
    itens: Array<VendaItem>;
}
export type VendaId = bigint;
export interface Fiado {
    id: FiadoId;
    total: bigint;
    data: Time;
    dataPagamento?: Time;
    clienteNome: string;
    itens: Array<VendaItem>;
    clienteTelefone: string;
    estado: EstadoFiado;
}
export interface VendaItem {
    produtoId: ProdutoId;
    preco: bigint;
    quantidade: bigint;
}
export interface Funcionario {
    id: FuncionarioId;
    ativo: boolean;
    nome: string;
    pinHash: Uint8Array;
    papel: Papel;
}
export interface Produto {
    id: ProdutoId;
    categoria: Categoria;
    ativo: boolean;
    nome: string;
    stockAtual: bigint;
    stockMinimo: bigint;
    unidade: Unidade;
    precoVenda: bigint;
    precoCusto: bigint;
}
export type FiadoId = bigint;
export enum Categoria {
    outros = "outros",
    bebida = "bebida",
    comida = "comida"
}
export enum EstadoFiado {
    pendente = "pendente",
    pago = "pago"
}
export enum MetodoPagamento {
    mpesa = "mpesa",
    outro = "outro",
    emola = "emola",
    dinheiro = "dinheiro"
}
export enum Papel {
    admin = "admin",
    caixa = "caixa",
    garcom = "garcom"
}
export enum Unidade {
    lata = "lata",
    garrafa = "garrafa",
    unidade = "unidade",
    prato = "prato"
}
export enum Variant_claro_escuro {
    claro = "claro",
    escuro = "escuro"
}
export interface backendInterface {
    atualizarConfiguracoes(novasConfig: Configuracoes): Promise<void>;
    consultarConfiguracoes(): Promise<Configuracoes>;
    consultarFiados(): Promise<Array<Fiado>>;
    consultarFuncionarios(): Promise<Array<Funcionario>>;
    consultarProdutos(): Promise<Array<Produto>>;
    consultarVendas(): Promise<Array<Venda>>;
    criarFiado(clienteNome: string, clienteTelefone: string, itens: Array<VendaItem>, total: bigint): Promise<Fiado>;
    criarFuncionario(nome: string, pinHash: Uint8Array, papel: Papel): Promise<Funcionario>;
    criarProduto(nome: string, categoria: Categoria, precoVenda: bigint, precoCusto: bigint, stockAtual: bigint, stockMinimo: bigint, unidade: Unidade): Promise<Produto>;
    criarVenda(itens: Array<VendaItem>, total: bigint, desconto: bigint, metodoPagamento: MetodoPagamento, funcionarioId: FuncionarioId, observacoes: string): Promise<Venda>;
}
import type { Categoria as _Categoria, Configuracoes as _Configuracoes, EstadoFiado as _EstadoFiado, Fiado as _Fiado, FiadoId as _FiadoId, Funcionario as _Funcionario, FuncionarioId as _FuncionarioId, MetodoPagamento as _MetodoPagamento, Papel as _Papel, Produto as _Produto, ProdutoId as _ProdutoId, Time as _Time, Unidade as _Unidade, Venda as _Venda, VendaId as _VendaId, VendaItem as _VendaItem } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async atualizarConfiguracoes(arg0: Configuracoes): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.atualizarConfiguracoes(to_candid_Configuracoes_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.atualizarConfiguracoes(to_candid_Configuracoes_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async consultarConfiguracoes(): Promise<Configuracoes> {
        if (this.processError) {
            try {
                const result = await this.actor.consultarConfiguracoes();
                return from_candid_Configuracoes_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.consultarConfiguracoes();
            return from_candid_Configuracoes_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async consultarFiados(): Promise<Array<Fiado>> {
        if (this.processError) {
            try {
                const result = await this.actor.consultarFiados();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.consultarFiados();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async consultarFuncionarios(): Promise<Array<Funcionario>> {
        if (this.processError) {
            try {
                const result = await this.actor.consultarFuncionarios();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.consultarFuncionarios();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async consultarProdutos(): Promise<Array<Produto>> {
        if (this.processError) {
            try {
                const result = await this.actor.consultarProdutos();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.consultarProdutos();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async consultarVendas(): Promise<Array<Venda>> {
        if (this.processError) {
            try {
                const result = await this.actor.consultarVendas();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.consultarVendas();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async criarFiado(arg0: string, arg1: string, arg2: Array<VendaItem>, arg3: bigint): Promise<Fiado> {
        if (this.processError) {
            try {
                const result = await this.actor.criarFiado(arg0, arg1, arg2, arg3);
                return from_candid_Fiado_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarFiado(arg0, arg1, arg2, arg3);
            return from_candid_Fiado_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async criarFuncionario(arg0: string, arg1: Uint8Array, arg2: Papel): Promise<Funcionario> {
        if (this.processError) {
            try {
                const result = await this.actor.criarFuncionario(arg0, arg1, to_candid_Papel_n30(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Funcionario_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarFuncionario(arg0, arg1, to_candid_Papel_n30(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Funcionario_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async criarProduto(arg0: string, arg1: Categoria, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: Unidade): Promise<Produto> {
        if (this.processError) {
            try {
                const result = await this.actor.criarProduto(arg0, to_candid_Categoria_n32(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_Unidade_n34(this._uploadFile, this._downloadFile, arg6));
                return from_candid_Produto_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarProduto(arg0, to_candid_Categoria_n32(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_Unidade_n34(this._uploadFile, this._downloadFile, arg6));
            return from_candid_Produto_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async criarVenda(arg0: Array<VendaItem>, arg1: bigint, arg2: bigint, arg3: MetodoPagamento, arg4: FuncionarioId, arg5: string): Promise<Venda> {
        if (this.processError) {
            try {
                const result = await this.actor.criarVenda(arg0, arg1, arg2, to_candid_MetodoPagamento_n36(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_Venda_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.criarVenda(arg0, arg1, arg2, to_candid_MetodoPagamento_n36(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_Venda_n26(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Categoria_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Categoria): Categoria {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Configuracoes_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Configuracoes): Configuracoes {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_EstadoFiado_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EstadoFiado): EstadoFiado {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Fiado_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fiado): Fiado {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Funcionario_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Funcionario): Funcionario {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MetodoPagamento_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetodoPagamento): MetodoPagamento {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Papel_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Papel): Papel {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Produto_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Produto): Produto {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Unidade_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Unidade): Unidade {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Venda_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Venda): Venda {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FuncionarioId;
    ativo: boolean;
    nome: string;
    pinHash: Uint8Array;
    papel: _Papel;
}): {
    id: FuncionarioId;
    ativo: boolean;
    nome: string;
    pinHash: Uint8Array;
    papel: Papel;
} {
    return {
        id: value.id,
        ativo: value.ativo,
        nome: value.nome,
        pinHash: value.pinHash,
        papel: from_candid_Papel_n16(_uploadFile, _downloadFile, value.papel)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProdutoId;
    categoria: _Categoria;
    ativo: boolean;
    nome: string;
    stockAtual: bigint;
    stockMinimo: bigint;
    unidade: _Unidade;
    precoVenda: bigint;
    precoCusto: bigint;
}): {
    id: ProdutoId;
    categoria: Categoria;
    ativo: boolean;
    nome: string;
    stockAtual: bigint;
    stockMinimo: bigint;
    unidade: Unidade;
    precoVenda: bigint;
    precoCusto: bigint;
} {
    return {
        id: value.id,
        categoria: from_candid_Categoria_n21(_uploadFile, _downloadFile, value.categoria),
        ativo: value.ativo,
        nome: value.nome,
        stockAtual: value.stockAtual,
        stockMinimo: value.stockMinimo,
        unidade: from_candid_Unidade_n23(_uploadFile, _downloadFile, value.unidade),
        precoVenda: value.precoVenda,
        precoCusto: value.precoCusto
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _VendaId;
    desconto: bigint;
    total: bigint;
    metodoPagamento: _MetodoPagamento;
    funcionarioId: _FuncionarioId;
    dataHora: _Time;
    observacoes: string;
    itens: Array<_VendaItem>;
}): {
    id: VendaId;
    desconto: bigint;
    total: bigint;
    metodoPagamento: MetodoPagamento;
    funcionarioId: FuncionarioId;
    dataHora: Time;
    observacoes: string;
    itens: Array<VendaItem>;
} {
    return {
        id: value.id,
        desconto: value.desconto,
        total: value.total,
        metodoPagamento: from_candid_MetodoPagamento_n28(_uploadFile, _downloadFile, value.metodoPagamento),
        funcionarioId: value.funcionarioId,
        dataHora: value.dataHora,
        observacoes: value.observacoes,
        itens: value.itens
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moeda: string;
    tema: {
        claro: null;
    } | {
        escuro: null;
    };
    nomeNegocio: string;
}): {
    moeda: string;
    tema: Variant_claro_escuro;
    nomeNegocio: string;
} {
    return {
        moeda: value.moeda,
        tema: from_candid_variant_n6(_uploadFile, _downloadFile, value.tema),
        nomeNegocio: value.nomeNegocio
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FiadoId;
    total: bigint;
    data: _Time;
    dataPagamento: [] | [_Time];
    clienteNome: string;
    itens: Array<_VendaItem>;
    clienteTelefone: string;
    estado: _EstadoFiado;
}): {
    id: FiadoId;
    total: bigint;
    data: Time;
    dataPagamento?: Time;
    clienteNome: string;
    itens: Array<VendaItem>;
    clienteTelefone: string;
    estado: EstadoFiado;
} {
    return {
        id: value.id,
        total: value.total,
        data: value.data,
        dataPagamento: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.dataPagamento)),
        clienteNome: value.clienteNome,
        itens: value.itens,
        clienteTelefone: value.clienteTelefone,
        estado: from_candid_EstadoFiado_n11(_uploadFile, _downloadFile, value.estado)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendente: null;
} | {
    pago: null;
}): EstadoFiado {
    return "pendente" in value ? EstadoFiado.pendente : "pago" in value ? EstadoFiado.pago : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    caixa: null;
} | {
    garcom: null;
}): Papel {
    return "admin" in value ? Papel.admin : "caixa" in value ? Papel.caixa : "garcom" in value ? Papel.garcom : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outros: null;
} | {
    bebida: null;
} | {
    comida: null;
}): Categoria {
    return "outros" in value ? Categoria.outros : "bebida" in value ? Categoria.bebida : "comida" in value ? Categoria.comida : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lata: null;
} | {
    garrafa: null;
} | {
    unidade: null;
} | {
    prato: null;
}): Unidade {
    return "lata" in value ? Unidade.lata : "garrafa" in value ? Unidade.garrafa : "unidade" in value ? Unidade.unidade : "prato" in value ? Unidade.prato : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mpesa: null;
} | {
    outro: null;
} | {
    emola: null;
} | {
    dinheiro: null;
}): MetodoPagamento {
    return "mpesa" in value ? MetodoPagamento.mpesa : "outro" in value ? MetodoPagamento.outro : "emola" in value ? MetodoPagamento.emola : "dinheiro" in value ? MetodoPagamento.dinheiro : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    claro: null;
} | {
    escuro: null;
}): Variant_claro_escuro {
    return "claro" in value ? Variant_claro_escuro.claro : "escuro" in value ? Variant_claro_escuro.escuro : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Funcionario>): Array<Funcionario> {
    return value.map((x)=>from_candid_Funcionario_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Produto>): Array<Produto> {
    return value.map((x)=>from_candid_Produto_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Venda>): Array<Venda> {
    return value.map((x)=>from_candid_Venda_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fiado>): Array<Fiado> {
    return value.map((x)=>from_candid_Fiado_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Categoria_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Categoria): _Categoria {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_Configuracoes_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Configuracoes): _Configuracoes {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_MetodoPagamento_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MetodoPagamento): _MetodoPagamento {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_Papel_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Papel): _Papel {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_Unidade_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Unidade): _Unidade {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moeda: string;
    tema: Variant_claro_escuro;
    nomeNegocio: string;
}): {
    moeda: string;
    tema: {
        claro: null;
    } | {
        escuro: null;
    };
    nomeNegocio: string;
} {
    return {
        moeda: value.moeda,
        tema: to_candid_variant_n3(_uploadFile, _downloadFile, value.tema),
        nomeNegocio: value.nomeNegocio
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_claro_escuro): {
    claro: null;
} | {
    escuro: null;
} {
    return value == Variant_claro_escuro.claro ? {
        claro: null
    } : value == Variant_claro_escuro.escuro ? {
        escuro: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Papel): {
    admin: null;
} | {
    caixa: null;
} | {
    garcom: null;
} {
    return value == Papel.admin ? {
        admin: null
    } : value == Papel.caixa ? {
        caixa: null
    } : value == Papel.garcom ? {
        garcom: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Categoria): {
    outros: null;
} | {
    bebida: null;
} | {
    comida: null;
} {
    return value == Categoria.outros ? {
        outros: null
    } : value == Categoria.bebida ? {
        bebida: null
    } : value == Categoria.comida ? {
        comida: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Unidade): {
    lata: null;
} | {
    garrafa: null;
} | {
    unidade: null;
} | {
    prato: null;
} {
    return value == Unidade.lata ? {
        lata: null
    } : value == Unidade.garrafa ? {
        garrafa: null
    } : value == Unidade.unidade ? {
        unidade: null
    } : value == Unidade.prato ? {
        prato: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MetodoPagamento): {
    mpesa: null;
} | {
    outro: null;
} | {
    emola: null;
} | {
    dinheiro: null;
} {
    return value == MetodoPagamento.mpesa ? {
        mpesa: null
    } : value == MetodoPagamento.outro ? {
        outro: null
    } : value == MetodoPagamento.emola ? {
        emola: null
    } : value == MetodoPagamento.dinheiro ? {
        dinheiro: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
